Importing cv2 (i.e. computer vision)

In [1]:
import cv2
import numpy as np

## Learning how to read images, videos and webcam ##

#### how to import an image 

In [2]:
img= cv2.imread("resources/lena.png")

cv2.imshow("output", img)
cv2.waitKey(0) #to cause delay in output , if value is 0, then infinitely delayed


-1

#### how to import a video

In [3]:
cap= cv2.VideoCapture("resources/test_video1.mp4")

while True:
    success, img =cap.read()   #variable 'success' is a boolean var
    cv2.imshow("Video", img)
    if cv2.waitKey(1) & 0xFF==ord('q'):
        break

error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:971: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'


#### how to use ur webcam

In [4]:
cap=cv2.VideoCapture(0)
cap.set(3,640)       #width
cap.set(4,480)       #length

while True:
    success, img =cap.read()   #variable 'success' is a boolean var
    cv2.imshow("Video", img)
    if cv2.waitKey(1) & 0xFF==ord('q'):
        break
cap.release() 
cv2.destroyAllWindows()

## Basic Functions

#### 1. COLOR_BGR2GRAY- converts to gray 


In [5]:
img= cv2.imread("resources/lena.png")

imgGray=cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow("Gray Image", imgGray)
cv2.waitKey(0)

-1

#### 2.GaussianBlur

In [6]:
imgBlur = cv2.GaussianBlur(imgGray, (21,21), 0)  # odd no.s only for (.,.)

cv2.imshow("Gray Image", imgGray)
cv2.imshow("Blur Image", imgBlur)
cv2.waitKey(0)

-1

#### 3.Canny

In [7]:
imgCanny= cv2.Canny(img, 150,200)
cv2.imshow("Canny img", imgCanny)
cv2.waitKey(0)

-1

#### 4.Dilate

In [8]:
kernel=np.ones((5,5), np.uint8)
imgDilate=cv2.dilate(imgCanny, kernel, iterations=1) #increasing iteration increases edge thickness
cv2.imshow("Dilated Image", imgDilate)
cv2.waitKey(0)

-1

#### 5. Erode - opp of dilate

In [9]:
imgEroded=cv2.erode(imgDilate, kernel, iterations=1)
cv2.imshow("Eroded image", imgEroded)
cv2.waitKey(0)

-1

#### Resizing our image

In [10]:
img=cv2.imread("resources/lambo.png")
print(img.shape)

(462, 623, 3)


In [11]:
imgResize= cv2.resize(img, (300,200))   # (width,height)

cv2.imshow("Image", img)
cv2.imshow("resized image", imgResize)
cv2.waitKey(0)

-1

#### Cropping our image

In [12]:
imgCropped = img[0:200, 200:500]  #[height, width]
cv2.imshow("Cropped image", imgCropped)
cv2.waitKey(0)

-1

## Shape and Texts

In [27]:
img=np.zeros((512, 512, 3), np.uint8)
print(img)

 #img[200:300, 100:300]= 0, 255 ,0  #B, G, R
cv2.imshow("Image", img)
cv2.waitKey(0)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


-1

#### 1.creating a line in the image
#### 2.Creating a rectangle in the image

In [28]:
#cv2.line(img, (0,0), (300,300),(0,255,0), 3)
cv2.line(img, (0,0), (img.shape[1], img.shape[0]),(0,255,0), 3)
cv2.rectangle(img, (0,0), (250,350), (0,0,255), 2) # For bordered rectangle

# for fully coloured rectangle , use cv2.FILLED instead of thickness

cv2.imshow("Image", img)
cv2.waitKey(0)

-1

#### 3.Creating a circle in the image

In [29]:
# Format:-  cv2.circle(img, center, radius, color, thickness)
cv2.circle(img, (400,50), 30, (255,255,0), 5)

cv2.imshow("Image", img)
cv2.waitKey(0)

-1

#### 4.Putting text on image

In [30]:
cv2.putText(img, "Hello world", (300,200), cv2.FONT_HERSHEY_COMPLEX, 1, (0,150,0), 1)
cv2.imshow("Image", img)
cv2.waitKey(0)

-1

## Warp Perspective

In [ ]:
img =cv2.imread("resources/cards.jpg")

width, height = 250, 350
pts1= np.float32([[111,219], [287,188],[154,482], [352,440]])  #find points of pixel through mspaint
pts2= np.float32([[0,0], [width,0], [0,height], [width,height]])
matrix=cv2.getPerspectiveTransform(pts1, pts2)
imgwarp= cv2.warpPerspective(img, matrix, (width, height))

cv2.imshow("Image", img)
cv2.imshow("output", imgwarp)
cv2.waitKey(0)

## Joining Images

In [37]:
img = cv2.imread("resources/lena.png")

imghor = np.hstack((img, img))
imgver= np.vstack((img,img))

cv2.imshow("horizontal", imghor)
cv2.imshow("vertical", imgver)
cv2.waitKey(0)


-1

## Color Detection

#### TASK: To detect orange colour in the image

In [ ]:
path="resources/lambo.png"

def empty(a):
    pass

cv2.namedWindow("Trackbars")
cv2.resizeWindow("Trackbars", 640, 240)
cv2.createTrackbar("Hue Min", "Trackbars", 3, 179, empty)
cv2.createTrackbar("Hue Max", "Trackbars", 17, 179, empty)
cv2.createTrackbar("Sat Min", "Trackbars", 140, 255, empty)
cv2.createTrackbar("Sat Max", "Trackbars", 255, 255, empty)
cv2.createTrackbar("Val Min", "Trackbars", 147, 255, empty)
cv2.createTrackbar("Val Max", "Trackbars", 255, 255, empty)



while True:
    img = cv2.imread(path)
    imgHSV= cv2.cvtColor(img , cv2.COLOR_BGR2HSV)
    h_min=cv2.getTrackbarPos("Hue Min", "Trackbars")
    h_max=cv2.getTrackbarPos("Hue Max", "Trackbars")
    s_min=cv2.getTrackbarPos("Sat Min", "Trackbars")
    s_max=cv2.getTrackbarPos("Sat Max", "Trackbars")
    v_min=cv2.getTrackbarPos("Val Min", "Trackbars")
    v_max=cv2.getTrackbarPos("Val Max", "Trackbars")
    
    lower=np.array([h_min, s_min, v_min])
    upper= np.array([h_max, s_max, v_max])
    mask=cv2.inRange(imgHSV, lower, upper)
    imgRes= cv2.bitwise_and(img, img , mask=mask)
    
    cv2.imshow("Image", img)
    cv2.imshow("HSV", imgHSV)
    cv2.imshow("Mask", mask)
    cv2.imshow("Result", imgRes)
    cv2.waitKey(1)

## Contours and shape detection

In [16]:
def stackImages(scale,imgArray):
    rows = len(imgArray)
    cols = len(imgArray[0])
    rowsAvailable = isinstance(imgArray[0], list)
    width = imgArray[0][0].shape[1]
    height = imgArray[0][0].shape[0]
    if rowsAvailable:
        for x in range ( 0, rows):
            for y in range(0, cols):
                if imgArray[x][y].shape[:2] == imgArray[0][0].shape [:2]:
                    imgArray[x][y] = cv2.resize(imgArray[x][y], (0, 0), None, scale, scale)
                else:
                    imgArray[x][y] = cv2.resize(imgArray[x][y], (imgArray[0][0].shape[1], imgArray[0][0].shape[0]), None, scale, scale)
                if len(imgArray[x][y].shape) == 2: imgArray[x][y]= cv2.cvtColor( imgArray[x][y], cv2.COLOR_GRAY2BGR)
        imageBlank = np.zeros((height, width, 3), np.uint8)
        hor = [imageBlank]*rows
        hor_con = [imageBlank]*rows
        for x in range(0, rows):
            hor[x] = np.hstack(imgArray[x])
        ver = np.vstack(hor)
    else:
        for x in range(0, rows):
            if imgArray[x].shape[:2] == imgArray[0].shape[:2]:
                imgArray[x] = cv2.resize(imgArray[x], (0, 0), None, scale, scale)
            else:
                imgArray[x] = cv2.resize(imgArray[x], (imgArray[0].shape[1], imgArray[0].shape[0]), None,scale, scale)
            if len(imgArray[x].shape) == 2: imgArray[x] = cv2.cvtColor(imgArray[x], cv2.COLOR_GRAY2BGR)
        hor= np.hstack(imgArray)
        ver = hor
    return ver


def getContours(img):
    contours, heirarchy = cv2.findContours(img, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    for cnt in contours:
        area= cv2.contourArea(cnt)
        print(area)
        if area>500:
            cv2.drawContours(imgContour, cnt, -1, (255,0,0), 3)
            peri = cv2.arcLength(cnt, True)
            # print(peri)
            approx= cv2.approxPolyDP(cnt, 0.02*peri, True)
            # print(len(approx))
            objCor= len(approx)
            x,y, w, h = cv2.boundingRect(approx)
            
            if objCor==3:objectType='Tri'
            elif objCor==4:
                aspRatio=w/float(h)
                if aspRatio>0.95 and aspRatio<1.05:
                    objectType='square'
                else:objectType='Rect'
            elif objCor>4 : objectType='Circle'
            else: objectType='None'
            cv2.rectangle(imgContour, (x,y), (x+w, y+h), (0, 255,0), 2)
            cv2.putText(imgContour, objectType, (x+(w//2)-10, y+(h//2)-10), cv2.FONT_HERSHEY_COMPLEX,0.7, (0, 0,0),2)
                        
                        
path="resources/shapes.png"
img= cv2.imread(path)
imgContour = img.copy()

imgGray= cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
imgBlur=cv2.GaussianBlur(imgGray,(7,7), 1)
imgcanny=cv2.Canny(imgBlur, 50,50)
imgblank= np.zeros_like(img)
getContours(imgcanny)

imgstack= stackImages(0.8, ([img, imgGray, imgBlur], [imgcanny, imgContour,imgblank]))
imgstack= cv2.resize(imgstack, (640, 480))

#cv2.imshow("Original", img)
#cv2.imshow("Gray", imgGray)
#cv2.imshow("Blur", imgBlur)
cv2.imshow("Stacked", imgstack)
cv2.waitKey(0)

3593.5
8619.0
10398.5
10236.0
1612.5
10402.0
6389.0
5629.0
3475.5
2270.5
3552.5
8674.0
2646.0
5690.5
10234.0
5712.0


-1

## Face Detection

In [ ]:
faceCascade=  cv2.CascadeClassifier("resources/haarcascades/haarcascade_frontalface_default.xml")
img = cv2.imread("resources/lena.png")
imgGray= cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces= faceCascade.detectMultiScale(imgGray, 1.1, 4)

for (x,y,w,h) in faces:
    cv2.rectangle(img , (x,y), (x+w, y+h), (255,0,0), 2)
    
cv2.imshow("Result", img)
cv2.waitKey(0)